package com.maya.useraccess.mapper;

import com.maya.useraccess.model.UserModel;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user
     *
     * @mbggenerated Tue Apr 16 02:09:01 CDT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user
     *
     * @mbggenerated Tue Apr 16 02:09:01 CDT 2019
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user
     *
     * @mbggenerated Tue Apr 16 02:09:01 CDT 2019
     */
    UserModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user
     *
     * @mbggenerated Tue Apr 16 02:09:01 CDT 2019
     */
    java.util.List<com.maya.useraccess.model.UserModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user
     *
     * @mbggenerated Tue Apr 16 02:09:01 CDT 2019
     */
    int updateByPrimaryKey(UserModel record);
}